# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gMzBgzK2jtcX773jvKaj3xIanfyzCeX
"""

import numpy as np #untuk simbol-simbol
from sklearn.linear_model #memanggil library 
import LinearRegression #jenis regresi

#database
#x = Data, y = target
x = [[1],[3],[5],[7],[9],[11],[13],[15],[17],[19]] 
y = [2, 6, 10, 14, 18, 22, 26, 30, 34, 38] #x dikali 2

regr = LinearRegression().fit(x,y) #untuk fitting grafik
regr.score(x, y) #untuk menentukan grafik

#data uji
predict = np.array([[15]]) #nilai yang di prediksi

#menampilkan data prediksi (menampilkan karakter)
print ("Prediksi") 
print ("input = ", predict)
print ("Output =", regr.predict(predict))

from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
import numpy as np 


#database 
#x = data, y = Target 
x = [[1],[3],[5],[7],[9],[11],[13],[15],[17],[19]]
y = [1, 9, 25, 49, 81, 121, 169, 225, 289, 361] #x dipangkat 2

#data uji 
predict = np.array([[21]]) #nilai yang di prediksi 
poly = PolynomialFeatures(degree=2) #ordo yang digunakan
x_=poly.fit_transform(x) #fitting prediksi sumbu
predict_ = poly.fit_transform(predict) #fitting jenis regresi
regr = linear_model.LinearRegression() #meregresi
regr.fit(x_,y) #menentukan grafik

#menampilkan data prediksi 
print ("Prediksi")
print ("input = ", predict)
print ("Output =", regr.predict(predict_))